export class BuilderNameConstants {
  static readonly HARA_A1: string = '@ohos/hara_A1'
  static readonly HARA_A2: string = '@ohos/hara_A2'
  static readonly HARB_B1: string = '@ohos/harb_B1'
  static readonly HARB_B2: string = '@ohos/harb_B2'
  static readonly HARB_B3: string = '@ohos/harb_B3'
  static readonly HARC_C1: string = '@ohos/harc_C1'
  static readonly HARC_C2: string = '@ohos/harc_C2'
  static readonly HAR_quickStart_qsPage: string = '@ohos/quickstart_qsPage'
  static readonly HAR_home_mainPage: string = '@ohos/home_mainPage'
  static readonly HAR_home_environmentalTip: string = '@ohos/home_environmentalTipPage'
  static readonly HAR_entry_adsPage: string = '@ohos/entry_adsPage'
}


export class RouterNameConstants {
  static readonly ENTRY_HAP: string = 'EntryHap_Router'
}