export class BuilderNameConstants {
  static readonly HAR_quickStart_qsPage: string = '@ohos/quickstart_qsPage'
  static readonly HAR_home_environmentalTip: string = '@ohos/home_environmentalTipPage'
  static readonly HAR_home_greenTravel: string = '@ohos/home_greenTravelPage'
  static readonly HAR_home_environmentalTips: string = '@ohos/home_environmentalTipsPage'
  static readonly HAR_home_houseApplication: string = '@ohos/home_houseApplicationPage'
  static readonly HAR_home_foodAndDrink: string = '@ohos/home_foodAndDrinkPage'
  static readonly HAR_home_detailCarbonEmission: string = '@ohos/home_detailEmissionPage'
  static readonly HAR_home_reduceCarbonEmissionMethod: string = '@ohos/home_reduceEmissionMethodPage'
  static readonly HAR_home_webNews: string = '@ohos/home_webNewsPage'
  static readonly HAR_tendency_lowFootprint: string = '@ohos/tendency_lowFootprintPage'
  static readonly HAR_tendency_lowTask: string = '@ohos/tendency_lowTaskPage'
  static readonly HAR_tendency_tomorrowTendency: string = '@ohos/tendency_tomorrowTendencyPage'
}


export class RouterNameConstants {
  static readonly ENTRY_HAP: string = 'EntryHap_Router'
}